import type { Course } from "@/components/customer/courses/course-card"

export const allCourses: Course[] = [
  {
    id: "1",
    image: "https://picsum.photos/seed/course1/600/400",
    category: "প্রোগ্রামিং",
    categoryColor: "bg-blue-100 text-blue-700",
    title: "Python দিয়ে প্রোগ্রামিং শিখুন — শূন্য থেকে বিশেষজ্ঞ",
    instructor: "তানভীর আহমেদ",
    instructorAvatar: "https://picsum.photos/seed/ins1/100/100",
    rating: 4.8,
    reviews: 1240,
    students: "১৫,৮০০+",
    duration: "৩২ ঘণ্টা",
    lessons: 96,
    level: "শিক্ষার্থী",
    levelColor: "bg-green-100 text-green-700",
    price: "৳ ৯৯৯",
    originalPrice: "৳ ১,৯৯৯",
    isBestseller: true,
  },
  {
    id: "2",
    image: "https://picsum.photos/seed/course2/600/400",
    category: "ওয়েব ডেভেলপমেন্ট",
    categoryColor: "bg-indigo-100 text-indigo-700",
    title: "React ও Next.js দিয়ে ফুল-স্ট্যাক ওয়েব ডেভেলপমেন্ট",
    instructor: "সানজিদা ইসলাম",
    instructorAvatar: "https://picsum.photos/seed/ins2/100/100",
    rating: 4.9,
    reviews: 876,
    students: "৯,৩০০+",
    duration: "৪৮ ঘণ্টা",
    lessons: 140,
    level: "মধ্যবর্তী",
    levelColor: "bg-amber-100 text-amber-700",
    price: "৳ ১,৪৯৯",
    originalPrice: "৳ ২,৯৯৯",
    isNew: true,
  },
  {
    id: "3",
    image: "https://picsum.photos/seed/course3/600/400",
    category: "ডিজাইন",
    categoryColor: "bg-pink-100 text-pink-700",
    title: "Figma দিয়ে UI/UX ডিজাইন — প্র্যাকটিক্যাল কোর্স",
    instructor: "রাহেলা খানম",
    instructorAvatar: "https://picsum.photos/seed/ins3/100/100",
    rating: 4.7,
    reviews: 654,
    students: "৬,২০০+",
    duration: "২৪ ঘণ্টা",
    lessons: 72,
    level: "শিক্ষার্থী",
    levelColor: "bg-green-100 text-green-700",
    price: "৳ ৭৯৯",
    originalPrice: "৳ ১,৪৯৯",
  },
  {
    id: "4",
    image: "https://picsum.photos/seed/course4/600/400",
    category: "ডেটা সায়েন্স",
    categoryColor: "bg-purple-100 text-purple-700",
    title: "Data Science ও Machine Learning — বাংলায় সম্পূর্ণ গাইড",
    instructor: "রিফাত হাসান",
    instructorAvatar: "https://picsum.photos/seed/ins4/100/100",
    rating: 4.9,
    reviews: 432,
    students: "৪,৫০০+",
    duration: "৬০ ঘণ্টা",
    lessons: 180,
    level: "মধ্যবর্তী",
    levelColor: "bg-amber-100 text-amber-700",
    price: "৳ ১,৭৯৯",
    originalPrice: "৳ ৩,৪৯৯",
    isBestseller: true,
  },
  {
    id: "5",
    image: "https://picsum.photos/seed/course5/600/400",
    category: "ভাষা",
    categoryColor: "bg-green-100 text-green-700",
    title: "Spoken English — দৈনন্দিন জীবনে সাবলীল ইংরেজি বলতে শিখুন",
    instructor: "নাফিস চৌধুরী",
    instructorAvatar: "https://picsum.photos/seed/ins5/100/100",
    rating: 4.8,
    reviews: 2100,
    students: "২২,০০০+",
    duration: "১৮ ঘণ্টা",
    lessons: 54,
    level: "শিক্ষার্থী",
    levelColor: "bg-green-100 text-green-700",
    price: "৳ ৪৯৯",
    originalPrice: "৳ ৯৯৯",
  },
  {
    id: "6",
    image: "https://picsum.photos/seed/course6/600/400",
    category: "ডিজিটাল মার্কেটিং",
    categoryColor: "bg-orange-100 text-orange-700",
    title: "Digital Marketing A–Z: SEO, Social Media ও Content Strategy",
    instructor: "আফিয়া জাহান",
    instructorAvatar: "https://picsum.photos/seed/ins6/100/100",
    rating: 4.6,
    reviews: 789,
    students: "৮,১০০+",
    duration: "২৮ ঘণ্টা",
    lessons: 84,
    level: "শিক্ষার্থী",
    levelColor: "bg-green-100 text-green-700",
    price: "৳ ৮৯৯",
    originalPrice: "৳ ১,৭৯৯",
    isNew: true,
  },
  {
    id: "7",
    image: "https://picsum.photos/seed/course7/600/400",
    category: "প্রোগ্রামিং",
    categoryColor: "bg-blue-100 text-blue-700",
    title: "JavaScript Mastery — আধুনিক ওয়েব ডেভেলপমেন্টের ভিত্তি",
    instructor: "মাহমুদ হাসান",
    instructorAvatar: "https://picsum.photos/seed/ins7/100/100",
    rating: 4.7,
    reviews: 980,
    students: "১১,৫০০+",
    duration: "৩৮ ঘণ্টা",
    lessons: 112,
    level: "শিক্ষার্থী",
    levelColor: "bg-green-100 text-green-700",
    price: "৳ ১,১৯৯",
    originalPrice: "৳ ২,৪৯৯",
  },
  {
    id: "8",
    image: "https://picsum.photos/seed/course8/600/400",
    category: "গ্রাফিক্স ডিজাইন",
    categoryColor: "bg-rose-100 text-rose-700",
    title: "Adobe Photoshop & Illustrator — প্রফেশনাল গ্রাফিক্স ডিজাইন",
    instructor: "সুমাইয়া আক্তার",
    instructorAvatar: "https://picsum.photos/seed/ins8/100/100",
    rating: 4.5,
    reviews: 543,
    students: "৫,৮০০+",
    duration: "২২ ঘণ্টা",
    lessons: 66,
    level: "শিক্ষার্থী",
    levelColor: "bg-green-100 text-green-700",
    price: "৳ ৬৯৯",
    originalPrice: "৳ ১,২৯৯",
  },
  {
    id: "9",
    image: "https://picsum.photos/seed/course9/600/400",
    category: "ডেভঅপস",
    categoryColor: "bg-cyan-100 text-cyan-700",
    title: "Docker ও Kubernetes — ক্লাউড ডেপ্লয়মেন্ট মাস্টারক্লাস",
    instructor: "আবির রহমান",
    instructorAvatar: "https://picsum.photos/seed/ins9/100/100",
    rating: 4.8,
    reviews: 312,
    students: "৩,২০০+",
    duration: "৪২ ঘণ্টা",
    lessons: 126,
    level: "অ্যাডভান্সড",
    levelColor: "bg-red-100 text-red-700",
    price: "৳ ১,৯৯৯",
    originalPrice: "৳ ৩,৯৯৯",
    isBestseller: true,
  },
  {
    id: "10",
    image: "https://picsum.photos/seed/course10/600/400",
    category: "ফ্রিল্যান্সিং",
    categoryColor: "bg-teal-100 text-teal-700",
    title: "Fiverr & Upwork দিয়ে ফ্রিল্যান্সিং শুরু করুন",
    instructor: "নুসরাত জাহান",
    instructorAvatar: "https://picsum.photos/seed/ins10/100/100",
    rating: 4.6,
    reviews: 1560,
    students: "১৮,৯০০+",
    duration: "১৫ ঘণ্টা",
    lessons: 45,
    level: "শিক্ষার্থী",
    levelColor: "bg-green-100 text-green-700",
    price: "৳ ৩৯৯",
    originalPrice: "৳ ৭৯৯",
    isNew: true,
  },
  {
    id: "11",
    image: "https://picsum.photos/seed/course11/600/400",
    category: "ওয়েব ডেভেলপমেন্ট",
    categoryColor: "bg-indigo-100 text-indigo-700",
    title: "Laravel দিয়ে PHP ব্যাকএন্ড ডেভেলপমেন্ট",
    instructor: "সাইফুল ইসলাম",
    instructorAvatar: "https://picsum.photos/seed/ins11/100/100",
    rating: 4.7,
    reviews: 421,
    students: "৪,৭০০+",
    duration: "৩৫ ঘণ্টা",
    lessons: 105,
    level: "মধ্যবর্তী",
    levelColor: "bg-amber-100 text-amber-700",
    price: "৳ ১,২৯৯",
    originalPrice: "৳ ২,৫৯৯",
  },
  {
    id: "12",
    image: "https://picsum.photos/seed/course12/600/400",
    category: "ভিডিও এডিটিং",
    categoryColor: "bg-violet-100 text-violet-700",
    title: "Premiere Pro ও After Effects — প্রফেশনাল ভিডিও এডিটিং",
    instructor: "রাফি করিম",
    instructorAvatar: "https://picsum.photos/seed/ins12/100/100",
    rating: 4.5,
    reviews: 678,
    students: "৭,৪০০+",
    duration: "২০ ঘণ্টা",
    lessons: 60,
    level: "শিক্ষার্থী",
    levelColor: "bg-green-100 text-green-700",
    price: "৳ ৫৯৯",
    originalPrice: "৳ ১,১৯৯",
    isFree: false,
  },
]

export const courseCategories = [
  "সব",
  "প্রোগ্রামিং",
  "ওয়েব ডেভেলপমেন্ট",
  "ডিজাইন",
  "গ্রাফিক্স ডিজাইন",
  "ডেটা সায়েন্স",
  "ডেভঅপস",
  "ডিজিটাল মার্কেটিং",
  "ভাষা",
  "ফ্রিল্যান্সিং",
  "ভিডিও এডিটিং",
]
